# Generated by Django 4.1.3 on 2022-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthernetFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_mac', models.CharField(max_length=255, verbose_name='dest_mac')),
                ('src_mac', models.CharField(max_length=255, verbose_name='src_mac')),
                ('proto', models.CharField(max_length=255, verbose_name='Protocol')),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flags', models.CharField(max_length=255, verbose_name='Flags')),
            ],
        ),
        migrations.CreateModel(
            name='IcmpPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='ICMP type')),
                ('code', models.CharField(max_length=255, verbose_name='Icmp code')),
                ('checksum', models.IntegerField(verbose_name='checksum')),
                ('data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IPv4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_ihl', models.IntegerField(verbose_name='IP Header Length')),
                ('version', models.IntegerField(verbose_name='version')),
                ('ihl', models.IntegerField(verbose_name='IP Header Length')),
                ('total_length', models.IntegerField(verbose_name='Total Length')),
                ('packed_id', models.IntegerField(verbose_name='Packet ID')),
                ('flags', models.CharField(max_length=255, verbose_name='Flags')),
                ('fragment_offset', models.IntegerField(verbose_name='Fragment offset')),
                ('ttl', models.IntegerField(verbose_name='Time to Live')),
                ('protocol_num', models.IntegerField(verbose_name='Protocol Number')),
                ('checksum', models.IntegerField(verbose_name='checksum')),
                ('source_address', models.CharField(max_length=255, verbose_name='IP source address')),
                ('dest_address', models.CharField(max_length=255, verbose_name='IP destination address')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto_name', models.CharField(max_length=255, verbose_name='Protocol Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tos', models.CharField(max_length=255, verbose_name='Time of Service')),
            ],
        ),
    ]
