# Generated by Django 4.1.3 on 2022-11-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0002_ipv4_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_port_tcp', models.IntegerField(verbose_name='Source TCP Port ')),
                ('dest_port_tcp', models.IntegerField(verbose_name='Destination Tcp Port')),
                ('sequence', models.IntegerField()),
                ('acknowledgement', models.IntegerField()),
                ('flag_urg', models.IntegerField()),
                ('flag_ack', models.IntegerField()),
                ('flag_psh', models.IntegerField()),
                ('flag_rst', models.IntegerField()),
                ('flag_syn', models.IntegerField()),
                ('flag_fin', models.IntegerField()),
                ('tcp_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Udp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_port_udp', models.IntegerField(verbose_name='Source UDP Port')),
                ('dest_port_udp', models.IntegerField(verbose_name='Destination Udp Port')),
                ('size_udp', models.IntegerField(verbose_name='size of Udp')),
                ('udp_data', models.CharField(max_length=255)),
            ],
        ),
    ]
