# Generated by Django 4.1.3 on 2022-11-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0003_tcp_udp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipv4',
            name='tos',
            field=models.IntegerField(null=True, verbose_name='Type Of Service'),
        ),
    ]
