# Generated by Django 4.1.3 on 2022-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0004_ipv4_tos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Protocol',
        ),
        migrations.RenameField(
            model_name='ethernetframe',
            old_name='proto',
            new_name='eth_proto',
        ),
        migrations.AddField(
            model_name='ethernetframe',
            name='eth_data',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
